# Generated by Django 3.0.8 on 2020-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropbox', models.CharField(blank=True, max_length=255)),
                ('google_token', models.CharField(blank=True, max_length=255)),
                ('google_projectid', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
