# Generated by Django 3.0.8 on 2020-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='one_client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='one_security',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='one_tenant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
